-- =====================================================
-- Matrice globale Plan/Rôle/Permissions
-- Définit les permissions pour chaque combinaison plan/rôle
-- =====================================================

CREATE TABLE IF NOT EXISTS plan_role_permissions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    plan_name TEXT NOT NULL REFERENCES plans(name) ON DELETE CASCADE,
    role TEXT NOT NULL CHECK (role IN ('owner', 'admin', 'accountant', 'agent', 'viewer')),
    permissions JSONB NOT NULL DEFAULT '{}',
    created_at TIMESTAMPTZ DEFAULT NOW(),
    updated_at TIMESTAMPTZ DEFAULT NOW(),
    
    -- Contrainte d'unicité : une seule entrée par combinaison plan/rôle
    UNIQUE(plan_name, role)
);

-- Index pour améliorer les performances
CREATE INDEX IF NOT EXISTS idx_plan_role_permissions_plan ON plan_role_permissions(plan_name);
CREATE INDEX IF NOT EXISTS idx_plan_role_permissions_role ON plan_role_permissions(role);
CREATE INDEX IF NOT EXISTS idx_plan_role_permissions_composite ON plan_role_permissions(plan_name, role);

-- Ajouter la table à la publication Supabase Realtime
ALTER PUBLICATION supabase_realtime ADD TABLE plan_role_permissions;

-- Commentaires
COMMENT ON TABLE plan_role_permissions IS 'Matrice globale définissant les permissions pour chaque combinaison plan/rôle';
COMMENT ON COLUMN plan_role_permissions.permissions IS 'Permissions stockées en JSONB, format: {"canViewAllTasks": true, "canCreateProperties": false, ...}';

-- =====================================================
-- Insertion de la matrice de permissions
-- =====================================================

-- FREEMIUM PLAN
-- Owner: Accès complet (mais limité par les fonctionnalités du plan)
INSERT INTO plan_role_permissions (plan_name, role, permissions) VALUES
('freemium', 'owner', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": false,
    "canViewReports": true,
    "canViewUsers": true,
    "canViewSettings": true,
    "canCreateTasks": true,
    "canCreateProperties": true,
    "canCreateUnits": true,
    "canCreateTenants": true,
    "canCreateLeases": true,
    "canCreatePayments": true,
    "canCreateJournalEntries": false,
    "canCreateUsers": false,
    "canSendMessages": true,
    "canEditTasks": true,
    "canEditOwnTasks": true,
    "canEditProperties": true,
    "canEditUnits": true,
    "canEditTenants": true,
    "canEditLeases": true,
    "canEditPayments": true,
    "canEditJournalEntries": false,
    "canEditUsers": false,
    "canEditSettings": true,
    "canDeleteTasks": true,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": true,
    "canDeleteUnits": true,
    "canDeleteTenants": true,
    "canDeleteLeases": true,
    "canDeletePayments": true,
    "canDeleteJournalEntries": false,
    "canDeleteUsers": false
}'::jsonb)
ON CONFLICT (plan_name, role) DO UPDATE SET
    permissions = EXCLUDED.permissions,
    updated_at = NOW();

-- Freemium: Pas d''autres rôles (limite à 1 utilisateur)
-- Les autres rôles auront les mêmes permissions que owner pour freemium

-- STARTER PLAN
INSERT INTO plan_role_permissions (plan_name, role, permissions) VALUES
('starter', 'owner', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": true,
    "canViewReports": true,
    "canViewUsers": true,
    "canViewSettings": true,
    "canCreateTasks": true,
    "canCreateProperties": true,
    "canCreateUnits": true,
    "canCreateTenants": true,
    "canCreateLeases": true,
    "canCreatePayments": true,
    "canCreateJournalEntries": true,
    "canCreateUsers": true,
    "canSendMessages": true,
    "canEditTasks": true,
    "canEditOwnTasks": true,
    "canEditProperties": true,
    "canEditUnits": true,
    "canEditTenants": true,
    "canEditLeases": true,
    "canEditPayments": true,
    "canEditJournalEntries": true,
    "canEditUsers": true,
    "canEditSettings": true,
    "canDeleteTasks": true,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": true,
    "canDeleteUnits": true,
    "canDeleteTenants": true,
    "canDeleteLeases": true,
    "canDeletePayments": false,
    "canDeleteJournalEntries": true,
    "canDeleteUsers": true
}'::jsonb),
('starter', 'admin', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": true,
    "canViewReports": true,
    "canViewUsers": true,
    "canViewSettings": true,
    "canCreateTasks": true,
    "canCreateProperties": true,
    "canCreateUnits": true,
    "canCreateTenants": true,
    "canCreateLeases": true,
    "canCreatePayments": true,
    "canCreateJournalEntries": true,
    "canCreateUsers": true,
    "canSendMessages": true,
    "canEditTasks": true,
    "canEditOwnTasks": true,
    "canEditProperties": true,
    "canEditUnits": true,
    "canEditTenants": true,
    "canEditLeases": true,
    "canEditPayments": true,
    "canEditJournalEntries": true,
    "canEditUsers": true,
    "canEditSettings": false,
    "canDeleteTasks": true,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": true,
    "canDeleteUnits": true,
    "canDeleteTenants": true,
    "canDeleteLeases": true,
    "canDeletePayments": false,
    "canDeleteJournalEntries": true,
    "canDeleteUsers": true
}'::jsonb),
('starter', 'accountant', '{
    "canViewAllTasks": false,
    "canViewOwnTasks": true,
    "canViewAllMessages": false,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": true,
    "canViewReports": true,
    "canViewUsers": false,
    "canViewSettings": false,
    "canCreateTasks": false,
    "canCreateProperties": false,
    "canCreateUnits": false,
    "canCreateTenants": false,
    "canCreateLeases": false,
    "canCreatePayments": true,
    "canCreateJournalEntries": true,
    "canCreateUsers": false,
    "canSendMessages": true,
    "canEditTasks": false,
    "canEditOwnTasks": true,
    "canEditProperties": false,
    "canEditUnits": false,
    "canEditTenants": false,
    "canEditLeases": false,
    "canEditPayments": true,
    "canEditJournalEntries": true,
    "canEditUsers": false,
    "canEditSettings": false,
    "canDeleteTasks": false,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": false,
    "canDeleteUnits": false,
    "canDeleteTenants": false,
    "canDeleteLeases": false,
    "canDeletePayments": false,
    "canDeleteJournalEntries": true,
    "canDeleteUsers": false
}'::jsonb),
('starter', 'agent', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": false,
    "canViewReports": true,
    "canViewUsers": false,
    "canViewSettings": false,
    "canCreateTasks": true,
    "canCreateProperties": true,
    "canCreateUnits": true,
    "canCreateTenants": true,
    "canCreateLeases": true,
    "canCreatePayments": true,
    "canCreateJournalEntries": false,
    "canCreateUsers": false,
    "canSendMessages": true,
    "canEditTasks": true,
    "canEditOwnTasks": true,
    "canEditProperties": true,
    "canEditUnits": true,
    "canEditTenants": true,
    "canEditLeases": true,
    "canEditPayments": true,
    "canEditJournalEntries": false,
    "canEditUsers": false,
    "canEditSettings": false,
    "canDeleteTasks": false,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": false,
    "canDeleteUnits": false,
    "canDeleteTenants": false,
    "canDeleteLeases": false,
    "canDeletePayments": false,
    "canDeleteJournalEntries": false,
    "canDeleteUsers": false
}'::jsonb),
('starter', 'viewer', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": false,
    "canViewReports": true,
    "canViewUsers": false,
    "canViewSettings": false,
    "canCreateTasks": false,
    "canCreateProperties": false,
    "canCreateUnits": false,
    "canCreateTenants": false,
    "canCreateLeases": false,
    "canCreatePayments": false,
    "canCreateJournalEntries": false,
    "canCreateUsers": false,
    "canSendMessages": false,
    "canEditTasks": false,
    "canEditOwnTasks": false,
    "canEditProperties": false,
    "canEditUnits": false,
    "canEditTenants": false,
    "canEditLeases": false,
    "canEditPayments": false,
    "canEditJournalEntries": false,
    "canEditUsers": false,
    "canEditSettings": false,
    "canDeleteTasks": false,
    "canDeleteOwnTasks": false,
    "canDeleteProperties": false,
    "canDeleteUnits": false,
    "canDeleteTenants": false,
    "canDeleteLeases": false,
    "canDeletePayments": false,
    "canDeleteJournalEntries": false,
    "canDeleteUsers": false
}'::jsonb)
ON CONFLICT (plan_name, role) DO UPDATE SET
    permissions = EXCLUDED.permissions,
    updated_at = NOW();

-- PRO PLAN (mêmes permissions que Starter mais avec plus de fonctionnalités disponibles)
INSERT INTO plan_role_permissions (plan_name, role, permissions)
SELECT 'pro', role, permissions
FROM plan_role_permissions
WHERE plan_name = 'starter'
ON CONFLICT (plan_name, role) DO UPDATE SET
    permissions = EXCLUDED.permissions,
    updated_at = NOW();

-- AGENCY PLAN (mêmes permissions que Pro)
INSERT INTO plan_role_permissions (plan_name, role, permissions)
SELECT 'agency', role, permissions
FROM plan_role_permissions
WHERE plan_name = 'pro'
ON CONFLICT (plan_name, role) DO UPDATE SET
    permissions = EXCLUDED.permissions,
    updated_at = NOW();

-- ENTERPRISE PLAN (accès complet pour tous les rôles sauf viewer)
INSERT INTO plan_role_permissions (plan_name, role, permissions) VALUES
('enterprise', 'owner', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": true,
    "canViewReports": true,
    "canViewUsers": true,
    "canViewSettings": true,
    "canCreateTasks": true,
    "canCreateProperties": true,
    "canCreateUnits": true,
    "canCreateTenants": true,
    "canCreateLeases": true,
    "canCreatePayments": true,
    "canCreateJournalEntries": true,
    "canCreateUsers": true,
    "canSendMessages": true,
    "canEditTasks": true,
    "canEditOwnTasks": true,
    "canEditProperties": true,
    "canEditUnits": true,
    "canEditTenants": true,
    "canEditLeases": true,
    "canEditPayments": true,
    "canEditJournalEntries": true,
    "canEditUsers": true,
    "canEditSettings": true,
    "canDeleteTasks": true,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": true,
    "canDeleteUnits": true,
    "canDeleteTenants": true,
    "canDeleteLeases": true,
    "canDeletePayments": true,
    "canDeleteJournalEntries": true,
    "canDeleteUsers": true
}'::jsonb),
('enterprise', 'admin', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": true,
    "canViewReports": true,
    "canViewUsers": true,
    "canViewSettings": true,
    "canCreateTasks": true,
    "canCreateProperties": true,
    "canCreateUnits": true,
    "canCreateTenants": true,
    "canCreateLeases": true,
    "canCreatePayments": true,
    "canCreateJournalEntries": true,
    "canCreateUsers": true,
    "canSendMessages": true,
    "canEditTasks": true,
    "canEditOwnTasks": true,
    "canEditProperties": true,
    "canEditUnits": true,
    "canEditTenants": true,
    "canEditLeases": true,
    "canEditPayments": true,
    "canEditJournalEntries": true,
    "canEditUsers": true,
    "canEditSettings": false,
    "canDeleteTasks": true,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": true,
    "canDeleteUnits": true,
    "canDeleteTenants": true,
    "canDeleteLeases": true,
    "canDeletePayments": true,
    "canDeleteJournalEntries": true,
    "canDeleteUsers": true
}'::jsonb),
('enterprise', 'accountant', '{
    "canViewAllTasks": false,
    "canViewOwnTasks": true,
    "canViewAllMessages": false,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": true,
    "canViewReports": true,
    "canViewUsers": false,
    "canViewSettings": false,
    "canCreateTasks": false,
    "canCreateProperties": false,
    "canCreateUnits": false,
    "canCreateTenants": false,
    "canCreateLeases": false,
    "canCreatePayments": true,
    "canCreateJournalEntries": true,
    "canCreateUsers": false,
    "canSendMessages": true,
    "canEditTasks": false,
    "canEditOwnTasks": true,
    "canEditProperties": false,
    "canEditUnits": false,
    "canEditTenants": false,
    "canEditLeases": false,
    "canEditPayments": true,
    "canEditJournalEntries": true,
    "canEditUsers": false,
    "canEditSettings": false,
    "canDeleteTasks": false,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": false,
    "canDeleteUnits": false,
    "canDeleteTenants": false,
    "canDeleteLeases": false,
    "canDeletePayments": false,
    "canDeleteJournalEntries": true,
    "canDeleteUsers": false
}'::jsonb),
('enterprise', 'agent', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": false,
    "canViewReports": true,
    "canViewUsers": false,
    "canViewSettings": false,
    "canCreateTasks": true,
    "canCreateProperties": true,
    "canCreateUnits": true,
    "canCreateTenants": true,
    "canCreateLeases": true,
    "canCreatePayments": true,
    "canCreateJournalEntries": false,
    "canCreateUsers": false,
    "canSendMessages": true,
    "canEditTasks": true,
    "canEditOwnTasks": true,
    "canEditProperties": true,
    "canEditUnits": true,
    "canEditTenants": true,
    "canEditLeases": true,
    "canEditPayments": true,
    "canEditJournalEntries": false,
    "canEditUsers": false,
    "canEditSettings": false,
    "canDeleteTasks": false,
    "canDeleteOwnTasks": true,
    "canDeleteProperties": false,
    "canDeleteUnits": false,
    "canDeleteTenants": false,
    "canDeleteLeases": false,
    "canDeletePayments": false,
    "canDeleteJournalEntries": false,
    "canDeleteUsers": false
}'::jsonb),
('enterprise', 'viewer', '{
    "canViewAllTasks": true,
    "canViewOwnTasks": true,
    "canViewAllMessages": true,
    "canViewOwnMessages": true,
    "canViewAllProperties": true,
    "canViewAllUnits": true,
    "canViewAllTenants": true,
    "canViewAllLeases": true,
    "canViewAllPayments": true,
    "canViewAccounting": false,
    "canViewReports": true,
    "canViewUsers": false,
    "canViewSettings": false,
    "canCreateTasks": false,
    "canCreateProperties": false,
    "canCreateUnits": false,
    "canCreateTenants": false,
    "canCreateLeases": false,
    "canCreatePayments": false,
    "canCreateJournalEntries": false,
    "canCreateUsers": false,
    "canSendMessages": false,
    "canEditTasks": false,
    "canEditOwnTasks": false,
    "canEditProperties": false,
    "canEditUnits": false,
    "canEditTenants": false,
    "canEditLeases": false,
    "canEditPayments": false,
    "canEditJournalEntries": false,
    "canEditUsers": false,
    "canEditSettings": false,
    "canDeleteTasks": false,
    "canDeleteOwnTasks": false,
    "canDeleteProperties": false,
    "canDeleteUnits": false,
    "canDeleteTenants": false,
    "canDeleteLeases": false,
    "canDeletePayments": false,
    "canDeleteJournalEntries": false,
    "canDeleteUsers": false
}'::jsonb)
ON CONFLICT (plan_name, role) DO UPDATE SET
    permissions = EXCLUDED.permissions,
    updated_at = NOW();

