-- =====================================================
-- Seed SYSCOHADA Accounts
-- Insert account data into accounts table
-- Category is extracted from the first digit of account_number
-- =====================================================

-- Clear existing accounts (optional - comment out if you want to keep existing data)
-- TRUNCATE TABLE accounts CASCADE;

-- Insert accounts data
INSERT INTO accounts (account_number, label, category, is_active) VALUES
('10', 'CAPITAL', '1', true),
('101', 'Capital social', '1', true),
('1011', 'Capital souscrit, non appelé', '1', true),
('1012', 'Capital souscrit, appelé, non versé', '1', true),
('1013', 'Capital souscrit, appelé, versé, non amorti', '1', true),
('1014', 'Capital souscrit, appelé, versé, amorti', '1', true),
('1018', 'Capital souscrit soumis à des conditions particulières', '1', true),
('102', 'CAPITAL PAR DOTATION', '1', true),
('1021', 'Dotation initiale', '1', true),
('1022', 'Dotations complémentaires', '1', true),
('1028', 'Autres dotations', '1', true),
('103', 'CAPITAL PERSONNEL', '1', true),
('104', 'COMPTE DE L''EXPLOITANT', '1', true),
('1041', 'Apports temporaires', '1', true),
('1042', 'Opérations courantes', '1', true),
('1043', 'Rémunérations, impôts et autres charges personnelles', '1', true),
('1047', 'Prélèvements d''autoconsommation', '1', true),
('1048', 'Autres prélèvements', '1', true),
('105', 'PRIMES LIÉES AUX CAPITAUX PROPRES', '1', true),
('1051', 'Primes d''émission', '1', true),
('1052', 'Primes d''apport', '1', true),
('1053', 'Primes de fusion', '1', true),
('1054', 'Primes de conversion', '1', true),
('1058', 'Autres primes', '1', true),
('106', 'ÉCARTS DE RÉÉVALUATION', '1', true),
('1061', 'Écarts de réévaluation légale', '1', true),
('1062', 'Écarts de réévaluation libre', '1', true),
('109', 'ACTIONNAIRES, CAPITAL SOUSCRIT, NON APPELÉ', '1', true),
('11', 'RÉSERVES', '1', true),
('111', 'RÉSERVE LÉGALE', '1', true),
('112', 'RÉSERVES STATUTAIRES OU CONTRACTUELLES', '1', true),
('113', 'RÉSERVES RÉGLEMENTÉES', '1', true),
('1131', 'Réserves de plus-values nettes à long terme', '1', true),
('1133', 'Réserves consécutives à l''octroi de subventions d''investissement', '1', true),
('1138', 'Autres réserves réglementées', '1', true),
('118', 'AUTRES RÉSERVES', '1', true),
('1181', 'Réserves facultatives', '1', true),
('1188', 'Réserves diverses', '1', true),
('12', 'REPORT À NOUVEAU', '1', true),
('121', 'REPORT À NOUVEAU CRÉDITEUR', '1', true),
('129', 'REPORT À NOUVEAU DÉBITEUR', '1', true),
('1291', 'Perte nette à reporter', '1', true),
('1292', 'Perte - Amortissements réputés différés', '1', true),
('13', 'RÉSULTAT NET DE L''EXERCICE', '1', true),
('130', 'RÉSULTAT EN INSTANCE D''AFFECTATION', '1', true),
('1301', 'Résultat en instance d''affectation : Bénéfice', '1', true),
('1309', 'Résultat en instance d''affectation : Perte', '1', true),
('131', 'RÉSULTAT NET : BÉNÉFICE', '1', true),
('132', 'MARGE BRUTE (M.B.)', '1', true),
('1321', 'Marge brute sur marchandises', '1', true),
('1322', 'Marge brute sur matières', '1', true),
('133', 'VALEUR AJOUTÉE (V.A.)', '1', true),
('134', 'EXCÉDENT BRUT D''EXPLOITATION (E.B.E.)', '1', true),
('135', 'RÉSULTAT D''EXPLOITATION (R.E.)', '1', true),
('136', 'RÉSULTAT FINANCIER (R.F.)', '1', true),
('137', 'RÉSULTAT DES ACTIVITÉS ORDINAIRES (R.A.O.)', '1', true),
('138', 'RÉSULTAT HORS ACTIVITÉS ORDINAIRES (R.H.A.O.)', '1', true),
('139', 'RÉSULTAT NET : PERTE', '1', true),
('14', 'SUBVENTIONS D''INVESTISSEMENT', '1', true),
('141', 'SUBVENTIONS D''ÉQUIPEMENT A', '1', true),
('1411', 'État', '1', true),
('1412', 'Régions', '1', true),
('1413', 'Départements', '1', true),
('1414', 'Communes et collectivités publiques décentralisées', '1', true),
('1415', 'Entreprises publiques ou mixtes', '1', true),
('1416', 'Entreprises et organismes privés', '1', true),
('1417', 'Organismes internationaux', '1', true),
('1418', 'Autres', '1', true),
('142', 'SUBVENTIONS D''ÉQUIPEMENT B', '1', true),
('148', 'AUTRES SUBVENTIONS D''INVESTISSEMENT', '1', true),
('15', 'PROVISIONS RÉGLEMENTÉES ET FONDS ASSIMILÉS', '1', true),
('151', 'AMORTISSEMENTS DÉROGATOIRES', '1', true),
('152', 'PLUS-VALUES DE CESSION À RÉINVESTIR', '1', true),
('153', 'FONDS RÉGLEMENTÉS', '1', true),
('1531', 'Fonds National', '1', true),
('1532', 'Prélèvement pour le Budget', '1', true),
('154', 'PROVISION SPÉCIALE DE RÉÉVALUATION', '1', true),
('155', 'PROVISIONS RÉGLEMENTÉES RELATIVES AUX IMMOBILISATIONS', '1', true),
('1551', 'Reconstitution des gisements miniers et pétroliers', '1', true),
('156', 'PROVISIONS RÉGLEMENTÉES RELATIVES AUX STOCKS', '1', true),
('1561', 'Hausse de prix', '1', true),
('1562', 'Fluctuation des cours', '1', true),
('157', 'PROVISIONS POUR INVESTISSEMENT', '1', true),
('158', 'AUTRES PROVISIONS ET FONDS RÉGLEMENTES', '1', true),
('16', 'EMPRUNTS ET DETTES ASSIMILÉES', '1', true),
('161', 'EMPRUNTS OBLIGATAIRES', '1', true),
('1611', 'Emprunts obligataires ordinaires', '1', true),
('1612', 'Emprunts obligataires convertibles', '1', true),
('1618', 'Autres emprunts obligataires', '1', true),
('162', 'EMPRUNTS ET DETTES AUPRÈS DES ÉTABLISSEMENTS DE CRÉDIT', '1', true),
('163', 'AVANCES REÇUES DE L''ÉTAT', '1', true),
('164', 'AVANCES REÇUES ET COMPTES COURANTS BLOQUÉS', '1', true),
('165', 'DÉPÔTS ET CAUTIONNEMENTS RECUS', '1', true),
('1651', 'Dépôts', '1', true),
('1652', 'Cautionnements', '1', true),
('166', 'INTÉRÊTS COURUS', '1', true),
('1661', 'sur emprunts obligataires', '1', true),
('1662', 'sur emprunts et dettes auprès des établissements de crédit', '1', true),
('1663', 'sur avances reçues de l''État', '1', true),
('1664', 'sur avances reçues et comptes courants bloqués', '1', true),
('1665', 'sur dépôts et cautionnements reçus', '1', true),
('1667', 'sur avances assorties de conditions particulières', '1', true),
('1668', 'sur autres emprunts et dettes', '1', true),
('167', 'AVANCES ASSORTIES DE CONDITIONS PARTICULIÈRES', '1', true),
('1671', 'Avances bloquées pour augmentation du capital', '1', true),
('1672', 'Avances conditionnées par l''État', '1', true),
('1673', 'Avances conditionnées par les autres organismes africains', '1', true),
('1674', 'Avances conditionnées par les organismes internationaux', '1', true),
('1676', 'Droits du concédant exigibles en nature', '1', true),
('168', 'AUTRES EMPRUNTS ET DETTES', '1', true),
('1681', 'Rentes viagères capitalisées', '1', true),
('1682', 'Billets de fonds', '1', true),
('1683', 'Dettes consécutives à des titres empruntés', '1', true),
('1684', 'Dettes du concédant exigibles en nature', '1', true),
('1685', 'Emprunts participatifs', '1', true),
('1686', 'Participation des travailleurs aux bénéfices', '1', true),
('17', 'DETTES DE CRÉDIT - BAIL ET CONTRATS ASSIMILÉS', '1', true),
('172', 'EMPRUNTS ÉQUIVALENTS DE CRÉDIT - BAIL IMMOBILIER', '1', true),
('173', 'EMPRUNTS ÉQUIVALENTS DE CRÉDIT - BAIL MOBILIER', '1', true),
('176', 'INTÉRÊTS COURUS', '1', true),
('1762', 'sur emprunts équivalents de crédit – bail immobilier', '1', true),
('1763', 'sur emprunts équivalents de crédit – bail mobilier', '1', true),
('1768', 'sur emprunts équivalents d''autres contrats', '1', true),
('178', 'EMPRUNTS ÉQUIVALENTS D''AUTRES CONTRATS', '1', true),
('18', 'DETTES LIÉES À DES PARTICIPATIONS ET COMPTES DE LIAISON DES ÉTABLISSEMENTS ET SOCIÉTÉS EN PARTICIPATION', '1', true),
('181', 'DETTES LIÉES À DES PARTICIPATIONS', '1', true),
('1811', 'Dettes liées à des participations (groupe)', '1', true),
('1812', 'Dettes liées à des participations (hors groupe)', '1', true),
('182', 'DETTES LIÉES À DES SOCIÉTÉS EN PARTICIPATION', '1', true),
('183', 'INTÉRÊTS COURUS SUR DETTES LIÉES À DES PARTICIPATIONS', '1', true),
('184', 'COMPTES PERMANENTS BLOQUÉS DES ÉTABLISSEMENTS ET SUCCURSALES', '1', true),
('185', 'COMPTES PERMANENTS NON BLOQUÉS DES ÉTABLISSEMENTS ET SUCCURSALES', '1', true),
('186', 'COMPTES DE LIAISON CHARGES', '1', true),
('187', 'COMPTES DE LIAISON PRODUITS', '1', true),
('188', 'COMPTES DE LIAISON DES SOCIÉTÉS EN PARTICIPATION', '1', true),
('19', 'PROVISIONS FINANCIÈRES POUR RISQUES ET CHARGES', '1', true),
('191', 'PROVISIONS POUR LITIGES', '1', true),
('192', 'PROVISIONS POUR GARANTIES DONNÉES AUX CLIENTS', '1', true),
('193', 'PROVISIONS POUR PERTES SUR MARCHÉS À ACHÈVEMENT FUTUR', '1', true),
('194', 'PROVISIONS POUR PERTES DE CHANGE', '1', true),
('195', 'PROVISIONS POUR IMPÔTS', '1', true),
('196', 'PROVISIONS POUR PENSIONS ET OBLIGATIONS SIMILAIRES', '1', true),
('197', 'PROVISIONS POUR CHARGES À RÉPARTIR SUR PLUSIEURS EXERCICES', '1', true),
('1971', 'Provisions pour grosses réparations', '1', true),
('198', 'AUTRES PROVISIONS FINANCIÈRES POUR RISQUES ET CHARGES', '1', true),
('1981', 'Provisions pour amendes et pénalités', '1', true),
('1982', 'Provisions pour renouvellement des immobilisations (entreprises concessionnaires)', '1', true),
('1983', 'Provisions de propre assureur', '1', true),
('1988', 'Autres provisions financières pour risques et charges', '1', true)
ON CONFLICT (account_number) DO UPDATE SET
  label = EXCLUDED.label,
  category = EXCLUDED.category,
  is_active = EXCLUDED.is_active;

-- Verify insertion
SELECT COUNT(*) as total_accounts, 
       COUNT(DISTINCT category) as categories_count
FROM accounts;

